- name: conditions for running tasks
  hosts: all
  tasks: 
    - name: running tasks on conditions
      debug: 
        msg: "this task is running under conditions"
      when: ansible_distribution == "Ubuntu"