- name: Registering vars
  hosts: all
  tasks:
    - name: Registering vars playbook
      shell: uptime
      register: OUTPUT
    
    - name: print output
      debug:
        msg: "{{OUTPUT.stdout}}"

    - name: print present working directory
      shell: pwd
      register: OUTPUT1
    
    - name: print working dir
      debug:
        msg: "{{OUTPUT1.stdout}}"